pull_request_rules:
  - name: Automatic merge
    conditions:
      - check-success=Build
      - files=members.yaml
      - "#files=1"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
